### ISSUE TITLE
Error (use-package): Cannot load ob-d2 Disable showing Disable logging

### ISSUE THREAD

**Issue by morgandavidson** [xcapaldi/ob-d2#2]
I use GNU Emacs 28.2 and d2 0.2.2 on GNU/Linux arch

I put `ob-d2.el` in `~/.emacs.d/manual/` and added the following line to my init:

```
(use-package ob-d2
  :ensure nil
  :load-path "~/.emacs.d/manual/ob-d2.el")

```

I have the following message when I load Emacs: 
`Error (use-package): Cannot load ob-d2 Disable showing Disable logging`

**Comment by xcapaldi** [comment]
I apologize. This was my misunderstanding of `use-package`'s `:load-path`. I thought it could be used to specify the load path of a package itself but reading the docs more thoroughly reveals it was just to add supporting files. Unfortunately if you aren't use a package manager like [straight.el](https://github.com/radian-software/straight.el) you will need to just put `ob-d2.el` in your load package (as you have already) and then add `(require 'ob-d2)` in your configuration. If you still get an errors, make sure `~/.emacs.d/manual/` is in your load path. You can add it with `(add-to-list 'load-path "~/.emacs.d/manual/")`. Let me know if this works for you. I've fixed the README in #3

**Comment by morgandavidson** [comment]
Thanks for your answer, it helped me to solve the issue.

Here is my working config:

```
  (use-package ob-d2
    :ensure nil
    :init (add-to-list 'load-path "~/.emacs.d/manual/")
    :config (require 'ob-d2))
```

**Comment by xcapaldi** [comment]
I've now packaged this on [Melpa](https://melpa.org/#/ob-d2) so if you have Melpa enabled, you can install with just

```Emacs Lisp
(use-package ob-d2
  :ensure t)
```

I also updated the readme to reflect this.
