### ISSUE TITLE
Flags don't seem to work?

### ISSUE THREAD

**Issue by Just-Insane** [xcapaldi/ob-d2#5]
I am using Doom Emacs, and I can get an image rendered, however, the `:flags` don't seem to be used by d2 when rendering.

For example, using the `:flags` example from the README:

![image](https://user-images.githubusercontent.com/15903884/236638347-a7bad1b6-e998-4633-b58e-bcf6a4e615c8.png)

The render I get is not the same as what is shown in the README.

**Comment by xcapaldi** [comment]
Hi, I don't use Doom but I've just tested this again on a minimal instance of Emacs and the render is still working properly with the flags. Can you give me the output of `d2 -v` from your terminal and the output of `(org-version)` in Emacs? Also if you pass the exact same command using the d2 CLI flow does it render properly? Just put `High Mem Instance -> EC2 <- High CPU Instance: Hosted By` into a file (`test.txt`) and run `d2 -t 101 -s test.txt`.

**Comment by xcapaldi** [comment]
Feel free to reopen this ticket if you still have any issues with the above

**Comment by LainLayer** [comment]
I am having the same issue
- `d2 -v` - `v0.5.1`
- `(org-version)` - `Org mode version 9.6.8 (release_9.6.8-3-g21171d @ <install path>)`

I have confirmed in htop that the flags aren't actually being passed to the d2 command.
![image](https://github.com/xcapaldi/ob-d2/assets/10339438/49361676-4b5a-42d0-a526-6771a2e4990d)

Im using vanilla emacs, tried several emacs versions

The source block Im using is `#+BEGIN_SRC d2 :file ./images/diagram2.png :flag -t 101`

The test you suggest with the EC2 example works:
![test](https://github.com/xcapaldi/ob-d2/assets/10339438/87851123-2284-4682-bed9-7433a4082648)

ran with `d2 -t 101 -s test.d2`

This is on arch linux, although i doubt that's relevant.

**Comment by l2yo** [comment]
Since the `org-babel-execute:d2` function is defined in both [`ob-d2`](https://github.com/xcapaldi/ob-d2/blob/5d197f8225a9fb4da997235b231abe30049c6825/ob-d2.el#L68) and [`d2-mode`](https://github.com/andorsk/d2-mode/blob/cbe7b16141bd80fe4344f0403e61fd7ee4e0fd89/d2-mode.el#L112), it will work if you uninstall d2-mode.

**Comment by LainLayer** [comment]
That worked, thank you

**Comment by Just-Insane** [comment]
Uninstalling `d2-mode` also resolved the issue for me, thanks!
